;;;; ./src/core/temp.lisp

(in-package :vlisp)

(defun vla-Add ())
(defun vla-Add3DFace ())
(defun vla-Add3DMesh ())
(defun vla-Add3DPoly ())
(defun vla-AddArc ())
(defun vla-AddAttribute ())
(defun vla-AddBox ())
(defun vla-AddCircle ())
(defun vla-AddCone ())
(defun vla-AddCustomInfo ())
(defun vla-AddCustomObject ())
(defun vla-AddCylinder ())
(defun vla-AddDim3PointAngular ())
(defun vla-AddDimAligned ())
(defun vla-AddDimAngular ())
(defun vla-AddDimArc ())
(defun vla-AddDimDiametric ())
(defun vla-AddDimOrdinate ())
(defun vla-AddDimRadial ())
(defun vla-AddDimRadialLarge ())
(defun vla-AddDimRotated ())
(defun vla-AddEllipse ())
(defun vla-AddEllipticalCone ())
(defun vla-AddEllipticalCylinder ())
(defun vla-AddExtrudedSolid ())
(defun vla-AddExtrudedSolidAlongPath ())
(defun vla-AddFitPoint ())
(defun vla-AddHatch ())
(defun vla-AddItems ())
(defun vla-AddLeader ())
(defun vla-AddLeaderLine ())
(defun vla-AddLeaderLineEx ())
(defun vla-AddLightWeightPolyline ())

(defun vla-AddLine ()
  "@b(Описание:) функция @b(vla-AddLine)
  (vla-AddLine modelSpace startPoint endPoint)
"
  )

(defun vla-AddMenuItem ())
(defun vla-AddMInsertBlock ())
(defun vla-AddMLeader ())
(defun vla-AddMLine ())
(defun vla-AddMText ())
(defun vla-AddObject ())
(defun vla-AddPoint ())
(defun vla-AddPolyfaceMesh ())
(defun vla-AddPolyline ())
(defun vla-AddPViewport ())
(defun vla-AddRaster ())
(defun vla-AddRay ())
(defun vla-AddRegion ())
(defun vla-AddRevolvedSolid ())
(defun vla-AddSection ())
(defun vla-AddSeparator ())
(defun vla-AddShape ())
(defun vla-AddSolid ())
(defun vla-AddSphere ())
(defun vla-AddSpline ())
(defun vla-AddSubMenu ())
(defun vla-AddTable ())
(defun vla-AddText ())
(defun vla-AddTolerance ())
(defun vla-AddToolbarButton ())
(defun vla-AddTorus ())
(defun vla-AddTrace ())
(defun vla-AddVertex ())
(defun vla-AddWedge ())
(defun vla-AddXline ())
(defun vla-AddXRecord ())
